language: php

php: ["5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "ej7vR8/Y0dA4EGu2k+kQSW4TPfg0OmRtnh0Dh9u2LeSzmxoATLL86qrgYRk9J8nEpdLEUN+VCaydzlLQrCxlyaVQd/ewLPv4lVU1gT2nprYzJX3nz8Os3/TaFUfLmsTXU7DHXI4WvFrmSvqCb4mN3ueYhplO/OZtLGjYRcGH1X4="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
